// Builds src/components/atoms/Icon/icons.generated.js from the .svg files in
// src/components/atoms/Icon/svgs/, so the Icon atom can inline them (and colour them with CSS).
// Runs automatically before `npm run dev` and `npm run build`.
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ICON_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'components', 'atoms', 'Icon');
const SVG_DIR = join(ICON_DIR, 'svgs');
const OUT = join(ICON_DIR, 'icons.generated.js');

const entries = readdirSync(SVG_DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort()
  .map((f) => {
    const svg = readFileSync(join(SVG_DIR, f), 'utf8')
      .trim()
      .replace(/\s+xmlns="[^"]+"/, '')
      .replaceAll('"#000"', '"currentColor"')
      .replace('<svg ', '<svg aria-hidden="true" focusable="false" ');
    return `  '${f.slice(0, -4)}': \`${svg}\`,`;
  });

const content =
  '// GENERATED by scripts/build-icons.mjs from the .svg files in ./svgs. Do not edit.\n' +
  '// Add or change an icon by editing its .svg file, then run `npm run icons` (or restart `npm run dev`).\n' +
  `export const ICONS = {\n${entries.join('\n')}\n};\n`;

if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== content) writeFileSync(OUT, content);
console.log(`icons: ${entries.length}`);
