"""
IKONIC site build.

Bundles each page's ES-module component tree into one classic script and all
component CSS into one stylesheet, so pages work from file:// (double-click)
as well as from any static host. No Node or npm needed.

    python tools/build.py           build once
    python tools/build.py --watch   rebuild whenever something in src/ changes

Source of truth stays in src/ — never edit files in dist/.
"""
import os
import re
import sys
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
DIST = os.path.join(ROOT, "dist")
ICON_DIR = os.path.join(SRC, "assets", "svgs", "icons")
ICON_REGISTRY = os.path.join(ICON_DIR, "index.js")

# page name -> entry module
PAGES = {
    "home": "src/pages/home/home.js",
    "distribution": "src/pages/distribution/distribution.js",
    "publishing": "src/pages/publishing/publishing.js",
    "advance": "src/pages/advance/advance.js",
    "pricing": "src/pages/pricing/pricing.js",
    "labels": "src/pages/labels/labels.js",
}
# stylesheet name -> entry
CSS_ENTRIES = {
    "site": "src/styles/index.css",
}

IMPORT_RE = re.compile(r"^import\s+(?:\{([^}]*)\}\s+from\s+)?'([^']+)';", re.M)
REEXPORT_RE = re.compile(r"^export\s+\{([^}]*)\}\s+from\s+'([^']+)';", re.M)
DECL_RE = re.compile(r"^export\s+(?:async\s+)?(function\*?|const|let|class)\s+([A-Za-z_$][\w$]*)", re.M)


def rel(path):
    return os.path.relpath(path, ROOT).replace("\\", "/")


def resolve(from_file, spec):
    return os.path.normpath(os.path.join(os.path.dirname(from_file), spec))


def names(spec_list):
    """'a, b as c' -> [('a', 'b'), ...] as (imported, local)"""
    out = []
    for part in spec_list.split(","):
        part = part.strip()
        if not part:
            continue
        if " as " in part:
            a, b = [p.strip() for p in part.split(" as ")]
            out.append((a, b))
        else:
            out.append((part, part))
    return out


# ---------- icons ----------
def build_icon_registry():
    """src/assets/svgs/icons/*.svg -> icons/index.js so the Icon atom can inline them."""
    entries = []
    for fname in sorted(os.listdir(ICON_DIR)):
        if not fname.endswith(".svg"):
            continue
        with open(os.path.join(ICON_DIR, fname), encoding="utf-8") as f:
            svg = f.read().strip()
        svg = re.sub(r'\s+xmlns="[^"]+"', "", svg)
        svg = svg.replace('"#000"', '"currentColor"')
        svg = svg.replace("<svg ", '<svg aria-hidden="true" focusable="false" ', 1)
        entries.append(f"  '{fname[:-4]}': `{svg}`,")
    content = (
        "// GENERATED by tools/build.py from the .svg files in this folder. Do not edit.\n"
        "// Add or change an icon by editing its .svg file, then run the build.\n"
        "export const ICONS = {\n" + "\n".join(entries) + "\n};\n"
    )
    old = open(ICON_REGISTRY, encoding="utf-8").read() if os.path.exists(ICON_REGISTRY) else ""
    if old != content:
        with open(ICON_REGISTRY, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
    return len(entries)


# ---------- JS ----------
def bundle_js(entry):
    order, seen, stack = [], set(), []

    def visit(path):
        if path in seen:
            return
        if path in stack:
            raise SystemExit(f"Circular import: {' -> '.join(rel(p) for p in stack + [path])}")
        stack.append(path)
        src = open(path, encoding="utf-8").read()
        for m in list(IMPORT_RE.finditer(src)) + list(REEXPORT_RE.finditer(src)):
            dep = resolve(path, m.group(2))
            if not os.path.exists(dep):
                raise SystemExit(f"{rel(path)}: cannot find '{m.group(2)}'")
            visit(dep)
        stack.pop()
        seen.add(path)
        order.append(path)

    visit(os.path.join(ROOT, entry))

    chunks = []
    for path in order:
        src = open(path, encoding="utf-8").read()
        key = rel(path)
        header, exports = [], []

        for m in IMPORT_RE.finditer(src):
            if m.group(1):
                dep = rel(resolve(path, m.group(2)))
                binds = ", ".join(a if a == b else f"{a}: {b}" for a, b in names(m.group(1)))
                header.append(f'const {{ {binds} }} = __m["{dep}"];')
        for m in REEXPORT_RE.finditer(src):
            dep = rel(resolve(path, m.group(2)))
            for a, b in names(m.group(1)):
                exports.append(f'{b}: __m["{dep}"].{a}')
        for m in DECL_RE.finditer(src):
            exports.append(m.group(2))

        body = IMPORT_RE.sub("", src)
        body = REEXPORT_RE.sub("", body)
        body = re.sub(r"^export\s+(?=(?:async\s+)?(?:function|const|let|class)\b)", "", body, flags=re.M)
        if "import.meta" in body or re.search(r"^\s*export\s", body, re.M):
            raise SystemExit(f"{key}: unsupported module syntax for the bundler")

        chunks.append(
            f'// ── {key}\n__m["{key}"] = (function () {{\n'
            + "\n".join(header) + "\n" + body.strip() + "\n"
            + f"return {{ {', '.join(exports)} }};\n}})();\n"
        )

    return (
        "/* GENERATED by tools/build.py — edit files in src/, then rebuild. */\n"
        "(function () {\n'use strict';\nconst __m = {};\n\n" + "\n".join(chunks) + "})();\n"
    )


# ---------- CSS ----------
CSS_IMPORT_RE = re.compile(r"@import\s+url\('([^']+)'\);")


def bundle_css(entry, seen=None):
    seen = seen if seen is not None else set()
    path = os.path.join(ROOT, entry) if not os.path.isabs(entry) else entry
    path = os.path.normpath(path)
    if path in seen:
        return ""
    seen.add(path)
    src = open(path, encoding="utf-8-sig").read()

    def repl(m):
        return bundle_css(resolve(path, m.group(1)), seen)

    out = CSS_IMPORT_RE.sub(repl, src)
    if re.search(r"url\((?!['\"]?(#|data:|https?:))", CSS_IMPORT_RE.sub("", src)):
        print(f"  warning: relative url() in {rel(path)} will not be rewritten")
    return f"/* {rel(path)} */\n{out.strip()}\n\n"


def build():
    started = time.time()
    os.makedirs(DIST, exist_ok=True)
    count = build_icon_registry()
    for page, entry in PAGES.items():
        with open(os.path.join(DIST, f"{page}.js"), "w", encoding="utf-8", newline="\n") as f:
            f.write(bundle_js(entry))
    for name, entry in CSS_ENTRIES.items():
        with open(os.path.join(DIST, f"{name}.css"), "w", encoding="utf-8", newline="\n") as f:
            f.write("/* GENERATED by tools/build.py — edit files in src/, then rebuild. */\n" + bundle_css(entry))
    css = ", ".join(f"{name}.css" for name in CSS_ENTRIES)
    print(f"built {', '.join(PAGES)} + {css} ({count} icons) in {time.time() - started:.2f}s")


def snapshot():
    state = {}
    for base, _, files in os.walk(SRC):
        for name in files:
            p = os.path.join(base, name)
            if p != ICON_REGISTRY:
                state[p] = os.path.getmtime(p)
    return state


if __name__ == "__main__":
    build()
    if "--watch" in sys.argv:
        print("watching src/ … (Ctrl+C to stop)")
        last = snapshot()
        while True:
            time.sleep(0.6)
            now = snapshot()
            if now != last:
                last = now
                try:
                    build()
                except SystemExit as e:
                    print(f"build failed: {e}")
